# Modified version of Code-Syncer workflow made.
name: Restart EpikHost Server

on: [ push ]

jobs:
  update-server:
    runs-on: ubuntu-latest 
    env:
      apiKey: ${{secrets.pterodactyl_panel_api_key}}
      id: ${{secrets.server_id}}
      config: ${{secrets.config}}
      adminKey: ${{secrets.admin_key}}

    steps:
      - name: "Update ConfigJSON on Server"
        run: |
          curl "https://panel.epikhost.xyz/api/application/servers/${{env.id}}/startup" \
          -H "Authorization: Bearer ${{env.adminKey}}" \
          -H "Content-Type: application/json" \
          -X POST \
          -d '{
            'startup': "if [[ -d .git ]] && [[ {{AUTO_UPDATE}} == '1' ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [[ ! -z ${UNNODE_PACKAGES} ]]; then /usr/local/bin/npm uninstall ${UNNODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install; fi; echo ${{env.config}} >> ./'Bot Files'/config.json; /usr/local/bin/node /home/container/{{BOT_JS_FILE}}"
          }'

      - name: Restart server
        run: |
          curl "https://panel.epikhost.xyz/api/client/servers/${{env.id}}/power" \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{env.apiKey}}' \
            -X POST \
            -d '{
            "signal": "restart"
            }'
        